### ISSUE TITLE
Páginas pares não ficam na margem esquerda

### ISSUE THREAD

**Issue by lobokoch** [luisbilecki/udesc-abntex#5]
Olá, segundo consta no [manual 2016 da UDESC](http://www.cct.udesc.br/arquivos/id_submenu/203/manual_2016_.pdf):

> No verso da página (páginas pares) o número de página é inserido dentro da margem
> esquerda superior. No anverso da página (páginas ímpares) o número é inserido na margem direita
> superior. Dessa forma, o número da página estará sempre na margem externa da mancha gráfica. 

Porém, ambas as páginas pares e ímpares estão ficando sempre na margem direita. É possível resolver esta questão?

Vi que tem o código abaixo no arquivo `udesc.sty` que parece que deveria tratar isso, porém parece não estar funcionando.
```
% ---
% Estilo de cabeçalho
% ---
\makepagestyle{eudesc}
  %%cabeçalhos
  \makeevenhead{eudesc} %%pagina par
     {\small\thepage} %topo par esquerda
     {}
     {}
  \makeoddhead{eudesc} %%pagina ímpar ou com oneside
     {}
     {}
     {\small\thepage} %topo direita impar```

**Comment by lobokoch** [comment]
Vi que esta ocorrendo este comportamento devido a estar configurado com `oneside` em vez de `twoside` no arquivo `Principal.tex`, comando `documentclass`.

**Comment by luisbilecki** [comment]
É isso mesmo pelo que me lembro.
Mas amanhã vou verificar essa questão.

**Comment by luisbilecki** [comment]
Conforme o Márcio mencionou, é só alterar de `oneside` para `twoside` no arquivo ` Principal.tex`, comando `documentclass`.

Portanto, deve ficar parecido com o código abaixo:

```
\documentclass[
	12pt,				% tamanho da fonte
	openright,			% capítulos começam em pág ímpar (insere página vazia caso preciso)
	%oneside,			
	twoside,                   %verso e anverso
	a4paper,			% tamanho do papel. 
	chapter=TITLE,		% títulos de capítulos convertidos em letras maiúsculas
	section=TITLE,		% títulos de seções convertidos em letras maiúsculas
	%subsection=TITLE,	% títulos de subseções convertidos em letras maiúsculas
	%subsubsection=TITLE,% títulos de subsubseções convertidos em letras maiúsculas
	% -- opções do pacote babel --
	english,			% idioma adicional para hifenização
	brazil,				% o último idioma é o principal do documento
	]{abntex2}
```
